### ISSUE TITLE
Cmake download

### ISSUE THREAD

**Issue by soumyajeet-kundu** [VinayakAlagwadi/Team1_Temperature_Conversion_Calculator#10]
please download cmake:   https://cmake.org/download/

**Comment by soumyajeet-kundu** [comment]
please download the zip file and open GUI.

**Comment by VinayakAlagwadi** [comment]
Make (or rather a Makefile) is a buildsystem - it drives the compiler and other build tools to build your code. CMake is a generator of buildsystems. It can produce Makefiles, it can produce Ninja build files, it can produce KDEvelop or Xcode projects, it can produce Visual Studio solutions.


Se

**Comment by PS99003576** [comment]
There is no need to install cmake application. We just have to add extension in  VS.

**Comment by VinayakAlagwadi** [comment]
> There is no need to install cmake application. We just have to add extension in VS.

sure

**Comment by Sirisha2598** [comment]
okay

**Comment by PS99003576** [comment]
Is MakeFile auto generated or it has to be typed?
